on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, self-hosted]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check System Deps
        uses: ./.github/actions/check_system_deps
      - name: Install deps
        uses: ./.github/actions/check_and_install_app_deps
      - name: Run Static Checks
        uses: ./.github/actions/run_static_checks
      - name: Run PyTest
        uses: ./.github/actions/run_unit_tests
